// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EVHW8qqOFyfBvWol8bPIvqHYwhlpWcQ',
    appId: '1:154572280636:web:2b00ed78867d1bac18c439',
    messagingSenderId: '154572280636',
    projectId: 'bubbymaterial',
    authDomain: 'bubbymaterial.firebaseapp.com',
    storageBucket: 'bubbymaterial.appspot.com',
    measurementId: 'G-E48YH5CYSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrs7fN_edCdad_b-M_Ag6uUAzXpcz0DSw',
    appId: '1:154572280636:android:cc0702eba55d58e118c439',
    messagingSenderId: '154572280636',
    projectId: 'bubbymaterial',
    storageBucket: 'bubbymaterial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtAFjh73quT1rvmgfAA1bc8rULw4dxTKc',
    appId: '1:154572280636:ios:1ef0d7134fd7f9cd18c439',
    messagingSenderId: '154572280636',
    projectId: 'bubbymaterial',
    storageBucket: 'bubbymaterial.appspot.com',
    iosClientId: '154572280636-695gd7e88uvkuq77ps0uurmr7jmjal7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtAFjh73quT1rvmgfAA1bc8rULw4dxTKc',
    appId: '1:154572280636:ios:1ef0d7134fd7f9cd18c439',
    messagingSenderId: '154572280636',
    projectId: 'bubbymaterial',
    storageBucket: 'bubbymaterial.appspot.com',
    iosClientId: '154572280636-695gd7e88uvkuq77ps0uurmr7jmjal7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptr',
  );
}
